swagger: "2.0"
info:
  description: En este archivo se configuran las rutas de acceso a la version 1 de manejo de usuarios.
  version: "1.0.0"
  title: api rest usuarios
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1/user"

# Paths supported by the server application
paths:
  /:
    get:
      operationId: backend.controllers.user.read
      tags:
        - "Users"
      parameters:
        - name: email
          in: query
          type: string
          required: false
      summary: "The user data structure supported by the server application"
      description: "Read the list of users"
      responses:
        200:
          description: "Successful read users list operation"
          schema:
            type: "string"
    post:
      operationId: backend.controllers.user.create
      tags:
        - "Create"
      description: "create a user"
      parameters:
        - name: user
          in: body
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
              lastname:
                type: string
              email:
                type: string
      responses:
        201:
          description: Successfully created user in list
  /{id}:
    get:
      operationId: backend.controllers.user.getOne
      tags:
        - user id
      parameters:
        - name: id
          in: path
          type: string
          required: True
      responses:
        201:
          description: Successfully get user id
  /confirm:
    post:
      operationId: backend.controllers.user.confirm
      tags:
        - confirmar usuario
      description: confirma datos de usuario
      parameters:
        - name: data
          in: body
          required: True
          schema:
            type: object
            properties:
              email:
                type: string
              phone:
                type: string
              date:
                type: string
              password:
                type: string
              nPassword:
                type: string
      responses:
        201:
          description: Successfully confirm user
