swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST api
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1/sesion"

# Paths supported by the server application
paths:
  /login:
    post:
      operationId: controllers.sesion.check
      tags:
        - "sesion"
      parameters:
        - name: sesion
          in: body
          required: True
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        201:
          description: "Successful read users list operation"
          schema:
            type: object

  /update_password:
    post:
      operationId: controllers.sesion.update
      tags:
        - password
      parameters:
        - name: sesion
          in: body
          required: True
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              newPassword:
                type: string
      responses:
        201:
          description: "Successful read users list operation"
          schema:
            type: object
